In [1]:
input = [1,2,3,4]
output = [2,4,6,8]


In [3]:
list(zip(input,output))

[(1, 2), (2, 4), (3, 6), (4, 8)]

In [2]:
w = 0.0
b = 0.0
lr = .01

In [4]:
for epoch in range(1000):
    total_loss = 0
    for x,y in zip(input,output):
        Y_pred = w*x+b
        error = Y_pred-y
        loss = error**2
        total_loss = total_loss + loss
        
        dw = 2*error*x
        db = 2*error
        
        w = w -lr*dw
        b = b - lr*db
        
    if epoch %10 ==0 :
        print(f"epoch {epoch} | Loss : {total_loss}  | w : {w} , b: {b}")
        
test_data = 7 
prediction = w*test_data + b 
print(prediction)   

epoch 0 | Loss : 79.87961196262401  | w : 0.97096256 , b: 0.33802464
epoch 10 | Loss : 0.23167004612544786  | w : 1.8256613181208952 , b: 0.5596735903428669
epoch 20 | Loss : 0.1802532439422414  | w : 1.8466864144525723 , b: 0.4933350597409343
epoch 30 | Loss : 0.13998891501896488  | w : 1.8648906985264255 , b: 0.4347575191083777
epoch 40 | Loss : 0.10871858414000884  | w : 1.880933299619277 , b: 0.3831353040251137
epoch 50 | Loss : 0.08443333195409766  | w : 1.8950710351359283 , b: 0.33764260473919433
epoch 60 | Loss : 0.06557285124030263  | w : 1.9075300849671393 , b: 0.29755161515366857
epoch 70 | Loss : 0.05092537177284956  | w : 1.9185097728042844 , b: 0.2622209473503665
epoch 80 | Loss : 0.03954980515791557  | w : 1.9281857550528785 , b: 0.23108537049551264
epoch 90 | Loss : 0.03071528068574688  | w : 1.9367128310375321 , b: 0.2036467681039125
epoch 100 | Loss : 0.023854187494407823  | w : 1.9442274195289089 , b: 0.17946616901901208
epoch 110 | Loss : 0.018525706043194708  | w : 

In [5]:
input = [1,2,3,4,5]
output = [2,4,6,8,10] 

In [6]:
w1 , b1 = .1,0.0
w2,b2 = -0.1 , 0.0
w3,w4 = .1 , .1 
b3 = 0.0
lr = .01

In [7]:
def relu(x):
    return max(0,x)

In [8]:
def relu_derivative(x):
    return 1 if x>0 else 0 

In [9]:
for epoch in range(100):
    total_loss = 0 
    for x,y in zip(input,output):
        z1 = w1*x + b1
        h1 = relu(z1)
        
        z2 = w2*x + b2
        h2 = relu(z2)
        
        Y_pred = w3*h1 + w4*h2 + b3
        
        error = Y_pred - y 
        loss  = error**2
        total_loss = total_loss + loss
        
        dl_dy = 2*error
        
        dw3 = dl_dy * h1
        dw4 = dl_dy * h2
        db3 = dl_dy
        
        dh1 = dl_dy * w3
        dh2 = dl_dy * w4
        
        dz1 = dh1* relu_derivative(z1)
        dz2 = dh2* relu_derivative(z2)
        
        dw1 = dz1 * x
        db1 = dz1
        
        dw2 = dz2 * x
        db2 = dz2
        
        w1 = w1 - lr*dw1
        w2 = w2 - lr*dw2
        w3 = w3 - lr*dw3
        w4 = w4 - lr*dw4
        
        
        b1 = b1 - lr*db1
        b2 = b2 - lr*db2
        b3 = b3 - lr*db3
        
    if epoch %10 ==0 :
        print(f"epoch {epoch} | Loss : {total_loss} ")
        
        
def prediction(x):
    z1 = w1*x + b1
    h1 = relu(z1)
        
    z2 = w2*x + b2
    h2 = relu(z2)
        
    y_output = w3*h1 + w4*h2 + b3
    return y_output     
                
prediction(9)     

epoch 0 | Loss : 197.58784675778605 
epoch 10 | Loss : 0.7822743866736906 
epoch 20 | Loss : 0.2777331306080438 
epoch 30 | Loss : 0.09441733364350127 
epoch 40 | Loss : 0.03110053083599192 
epoch 50 | Loss : 0.010038059173204952 
epoch 60 | Loss : 0.00320027527189278 
epoch 70 | Loss : 0.0010129806992875082 
epoch 80 | Loss : 0.0003193181207800499 
epoch 90 | Loss : 0.00010042211687133479 


17.99692772369434

In [18]:
import tensorflow as tf 
import numpy as np 

In [19]:
input

[1, 2, 3, 4, 5]

In [20]:
output

[2, 4, 6, 8, 10]

In [21]:
import numpy as np
x = np.array(input,dtype=float)
y = np.array(output, dtype=float)

In [22]:
model = tf.keras.Sequential([tf.keras.layers.Dense(20,activation='relu',input_shape = [1]),
                    tf.keras.layers.Dense(1)])

c:\Users\raksh\AppData\Local\anaconda3\envs\genai\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=.001),loss='mean_squared_error')

In [ ]:
model.fit(x,y,epochs=1000,verbose=1)
model.save("gen_ai_first.h5")


Epoch 1/1000


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 699ms/step - loss: 84.3418
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 76.1888
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 69.4277
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 63.9018
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 59.3725
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 55.5582
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 52.3150
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 49.3730
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 46.6729
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 44.1680
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 41.8218
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 39.6098
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 37.5132
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 35.5623
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 33.8641


In [31]:
model.predict(np.array([[90]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


array([[171.23837]], dtype=float32)

In [32]:
data = 'help'
char2idx = {'h':0 , 'e' : 1 , "l":2 , "p" :3}
idx2char = {v : k for k , v in char2idx.items()}

In [33]:
char2idx

{'h': 0, 'e': 1, 'l': 2, 'p': 3}

In [34]:
idx2char

{0: 'h', 1: 'e', 2: 'l', 3: 'p'}

In [35]:
input_seq = [char2idx[c] for c in data[:-1]]
target_seq = [char2idx[c] for c in data [1:]]

In [36]:
target_seq

[1, 2, 3]

In [37]:
input_seq   

[0, 1, 2]

In [38]:
x = tf.one_hot(input_seq,depth=4 )
x = tf.expand_dims(x , axis=0)
y = tf.expand_dims(target_seq , axis=0)

In [39]:
x

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

In [40]:
y

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [41]:
model = tf.keras.Sequential([tf.keras.layers.LSTM(8,return_sequences=True , input_shape =(3,4) ) , 
                     tf.keras.layers.Dense(4,activation='linear')])

c:\Users\raksh\AppData\Local\anaconda3\envs\genai\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [42]:
model.compile(optimizer='adam' ,loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [43]:
for epoch in range(201):
    model.train_on_batch(x,y)
    
    if epoch % 50  == 0 :
        output = model(x)
        print(output)
        pred = tf.argmax(output,axis = -1).numpy()[0]
        pred_char = "".join([idx2char[i] for i in pred] )
        print(f"epoch : {epoch} , prediction : {pred_char} , loss : {loss} ")

tf.Tensor(
[[[ 0.05281113 -0.11898186  0.1376808   0.00191022]
  [ 0.06228043 -0.1384154   0.1731213   0.07092573]
  [ 0.03681976  0.01548021  0.06488243  0.03669585]]], shape=(1, 3, 4), dtype=float32)
epoch : 0 , prediction : lll , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.03319173 -0.02884579  0.2072102   0.05991681]
  [-0.03655896 -0.09725054  0.33858907  0.1440021 ]
  [-0.04330247  0.06799817  0.17047232  0.20778766]]], shape=(1, 3, 4), dtype=float32)
epoch : 50 , prediction : llp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.11710906  0.05862897  0.29881793  0.14789538]
  [-0.15622087 -0.07769421  0.5731597   0.29759818]
  [-0.15243326  0.11692774  0.31482378  0.55372685]]], shape=(1, 3, 4), dtype=float32)
epoch : 100 , prediction : llp , loss : 5.823832244906861e-07 
tf.Tensor(
[[[-0.2315315   0.16067904  0.39404333  0.23273952]
  [-0.37032685 -0.09327099  0.89748925  0.54529697]
  [-0.39988142  0.08568002  0.50324094  1.2638017 ]]], shape=(1, 3, 4), dtype=float32)
epoch 

In [44]:
model.save('lstm.h5')